<ul tabindex="0" class="dropdown-content bg-base-300 rounded-box z-[1] w-52 p-2 shadow-2xl text-base bg-glass max-h-60 overflow-auto">
  <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start text-primary" value="light" id="theme-light" aria-label="Light"/></li>
  <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start text-primary" value="dark" id="theme-dark" aria-label="Dark"/></li>
  <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start text-primary" value="cupcake" id="theme-cupcake" aria-label="Cupcake"/></li>
  <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start text-primary" value="bumblebee" id="theme-bumblebee" aria-label="Bumblebee"/></li>
  <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start text-primary" value="emerald" id="theme-emerald" aria-label="Emerald"/></li>
  <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start text-primary" value="corporate" id="theme-corporate" aria-label="Corporate"/></li>
  <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start text-primary" value="synthwave" id="theme-synthwave" aria-label="Synthwave"/></li>
  <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start text-primary" value="retro" id="theme-retro" aria-label="Retro"/></li>
  <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start text-primary" value="cyberpunk" id="theme-cyberpunk" aria-label="Cyberpunk"/></li>
  <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start text-primary" value="valentine" id="theme-valentine" aria-label="Valentine"/></li>
  <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start text-primary" value="halloween" id="theme-halloween" aria-label="Halloween"/></li>
  <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start text-primary" value="garden" id="theme-garden" aria-label="Garden"/></li>
  <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start text-primary" value="forest" id="theme-forest" aria-label="Forest"/></li>
  <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start text-primary" value="aqua" id="theme-aqua" aria-label="Aqua"/></li>
  <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start text-primary" value="night" id="theme-night" aria-label="Night"/></li>
  <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start text-primary" value="business" id="theme-business" aria-label="Business"/></li>
  <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start text-primary" value="sunset" id="theme-sunset" aria-label="Sunset"/></li>
</ul>